# Generated by Django 5.2.3 on 2025-07-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_no',
        ),
    ]
